title: Rajashekar Eppalapelly
logo: /assets/img/Raj_pic.jpeg
description: An organized and goal oriented individual with around 10+ years of experience in Software development. 
Being passionate about technology, I always look for innovative techniques to build the software products. I 
have been highly effective in leading team with strong communication and interpersonal skills.
show_downloads: true
google_analytics:
